# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish pdfjs-dist

on:
  push:
    branches:
      - master

jobs:
  replace-package-json-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: install dependencies
        run: npm i && npm i gulp -D
      - name: build
        run: npx gulp dist-pre
      - name: change package name
        working-directory: build/dist
        run: |
          sed -i 's/"name": "pdfjs-dist"/"name": "@orca-fe\/pdfjs-dist-browserify"/g' ./package.json
          cat ./package.json
      - name: replace require canvas
        working-directory: build/dist
        run: |
          sed -i 's/require("canvas")/{}/g' ./build/pdf.js
          sed -i 's/require("canvas")/{}/g' ./build/pdf.min.js
      - working-directory: build/dist
        run: pwd && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
